config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  resources :customers
  resources :rooms do
      collection do
        get  :search
        post :new_search
        get  :show_search
        get  :search_by_room_type_id
      end

  end 
  resources :room_types
  resources :bookings
  resources :billings

  get 'welcome/index'

  # root 'welcome#index'
  root 'sessions#new'
  
  get 'login', to: 'sessions#new'
  
  delete 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking

  include Mongoid::Document

  field :check_in, type: Date
  field :check_out, type: Date
  field :adults, type: Integer
  field :children, type: Integer
  field :room_ids, type: Array, default: []
  field :room_type_ids, type: Array, default: []
  field :customer_id, type: Integer
  field :count, type: Hash, default: {}

  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :adults, presence: true, numericality: { only_integer: true, allow_nil: false }
  validates :children, presence: true, numericality: { only_integer: true, allow_nil: false }

  belongs_to  :customer
  
  has_and_belongs_to_many :rooms
  has_and_belongs_to_many :room_types

  # accepts_nested_attributes_for :rooms

end

app/models/customer.rb
class Customer

  include Mongoid::Document
  field :name, type: String
  field :phone, type: String
  field :email, type: String
  field :adhaar_id, type: String

  validates :name, presence: true, length: { in: 5..100}

  has_many :bookings
  has_many :rooms

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

	before_action :must_login

	def index

		@bookings 	= Booking.all
		@rooms 		= Room.all
		@customers 	= Customer.all

		respond_to do |format|
			format.html
			format.js
		end
	end

	def create
		
		@booking = Booking.new( booking_params )
		
		@room_ids 	   = booking_params["room_ids"].map(&:to_s)
		@room_type_ids = booking_params["room_type_ids"]

		@rooms 	    = Room.all
		@room_types = RoomType.all

		@relations 	 = Hash.new{|hsh,key| hsh[key] = [] }
		@room_counts = Hash.new


		@rooms.each do |room|
			
			room_id = room.id.to_s
			puts room.room_type_id
			if @room_ids.include?(room_id)
				@relations[room.room_type_id].push(room.id)
			end
			
		end

		@relations.each do |key,values|
			@room_counts[key.to_s] = values.count
		end

		@booking.count = @room_counts

		if @booking.save
			self.index
		else 
			respond_to do |format|
				format.html
				format.js
			end
		end	

	end

	def new 

		@booking = Booking.new

		respond_to do |format|
			format.html
			format.js
		end

	end

	def edit
		@booking = Booking.find( params[:id] )

		respond_to do |format|
			format.html
			format.js
		end
	end

	def update 

		@booking = Booking.find( params[:id] )

		if @booking.update
			self.index
		else
			render 'edit'
		end
	end

	def destroy

		@booking = Booking.find( params[:id] )

		@booking.destroy

		self.index

	end

	private

		def booking_params
			params.require(:booking).permit( :check_in, :check_out, :adults, :children, :customer_id,:room_ids => [], :room_type_ids => [] )
		end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_edit.html.erb
<h1>Editing Booking</h1>
<%= render 'form'%>

app/views/bookings/_form.html.erb
<div class="well width60 center">
<%= form_for @booking, :html => {:id => "book_a_room", :multipart => true, :remote => true } do |f|%>

    <% if @booking.errors.any? %>
        <div id="error_explanation">
          <h2>
          <%= pluralize( @booking.errors.count, "error" )%> Prohibited this booking from saved:
          </h2>
          <ul>
            <% @booking.errors.full_messages.each do |msg|%>
              <li><%=msg %></li>
            <% end %>
          </ul>
        </div>
    <% end%>
    <div class="container-fluid">
        <div class="form-group row">
          <div class="col-sm-4">
            <%= f.label :check_in %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :check_in, 'data-behaviour' => 'datepicker' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-4">
            <%= f.label :check_out %>
          </div>
           <div class="col-sm-8">
            <%= f.text_field :check_out, 'data-behaviour' => 'datepicker' %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-4">
            <%= f.label :adults %>
          </div>
          <div class="col-sm-8">
            <%=f.select :adults, options_for_select(1..5)%>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-4">
            <%= f.label :children %>
          </div>
          <div class="col-sm-8">
            <%=f.select :children, options_for_select(1..5)%>
          </div>

        </div>

        <div class="form-group row">
          <div class="table-responsive">
            <table class="table-bordered table">
               <thead>
                  <tr>
                    <th class="col-md-1"></th>
                    <th class="col-md-3">Room types</th>
                    <th class="col-md-8">Rooms</th>
                  </tr>
                </thead>

                <tbody>
                 <%= f.collection_check_boxes( :room_type_ids,RoomType.all,:id,:name,{:include_hidden => false,},{:class => 'chk_room_type'}) do |b| %>
                  <tr>
                    <!-- <tr><%= b.check_box %><%= b.label %></tr> -->
                    <%= content_tag( :td, b.check_box, class: "checkbox-wrap" )%>
                    <%= content_tag( :td, b.label, class: "label-wrap" )%>
                    <%= content_tag( :td, nil, class: "room_name", id: "room_" + b.value ) %>
                  </tr>
                <% end %>
                </tbody>
            </table>
          </div>
        </div>

         <div class="form-group row">
            <div class="col-sm-4">
              <%= f.label :select_customer %>
            </div>
            <div class="col-sm-4">
               <%= collection_select(:booking, :customer_id, Customer.all, :id, :name ) %>
            </div>
            <div class="col-sm-4">
              <%= link_to "Create customer", new_customer_path, remote: true, id:'list_rooms', class:'btn btn-info btn-md' %>
            </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-6">
            <%= link_to 'Back', bookings_path , :class => "btn btn-danger left", remote: true %>
          </div>
          <div class="col-sm-6">
          </div>
           <div class="col-sm-6">
            <%= f.submit :class => 'btn btn-info right', :id => "create_customer" %>
          </div>
        </div>
      </div>
<% end %>
</div>
<%= javascript_include_tag('bookings.js') %>

app/views/bookings/_index.html.erb
<div class="row">
    <div class="col-sm-9">
      <div class="well">
        <div class="row">
            <div class="col-sm-10 bottom20"><h3>Listing bookings</h3></div>
            
            <% if @rooms.any? %>
              <div class="col-sm-2"><%= link_to "Book a room", new_booking_path, remote: true, id:'list_bookings', class:'btn btn-success btn-md float-right' %>
              </div>
            <% else%>
              <div class="alert alert-warning col-sm-6">
                <strong>Warning!</strong> Add at least one room to make a booking.
              </div>
            <% end %>
          <table class="table table-bordered">
              <tr>
                <th>Check in</th>
                <th>Check out</th>
                <th>Adults</th>
                <th>Childrens</th>
                <th>Room number</th>
                <th>Customer name</th>
                <th colspan="3" class="text-center">Action</th>
              </tr>

              <% if true == @bookings.any? %>
                  <% @bookings.each do |booking|%>
                    <tr>
                        <td><%=booking.check_in %></td>
                        <td><%=booking.check_out %></td>
                        <td><%=booking.adults %></td>
                        <td><%=booking.children %></td>
                        <td>
                          <ul>
                            <% booking.room_ids.each do |room_id| %>
                              <% room = @rooms.find( room_id )%>
                              <li><%=room.room_number %></li>
                            <% end%>
                          </ul>
                        </td>
                        <% customer = @customers.find( booking.customer_id ) %>
                        <td>
                          <%=customer.name%>
                        </td>
                        <td>
                          <%= link_to 'Edit', edit_booking_path( booking ), :class => "glyphicon glyphicon-pencil", remote:true %>
                        </td>
                        <td>
                          <%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' }, remote:true %>
                        </td>
                        <td>
                          <%= link_to 'Generate bill', edit_billing_path( booking.id ), remote: true %>
                        </td>
                    </tr>
                  <% end %>
              <% else %>
                  <tr>
                    <td colspan="7" class="text-center bg-info">
                      <b>No record found</b>
                    </td>
                  </tr>
              <% end%>
        </table>
      </div>
  </div>
</div>
  <div class="col-sm-3 well">
    <h4>Search by</h4>
    <input class="form-control" id="myInput" type="text" placeholder="Customer name">
    <br>
    <div class="row">
      <div class="col-sm-6">
        <p>Check in</p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-6">
        <div class="dropdown">
      <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Min<span class="caret"></span></button>
        <ul class="dropdown-menu">
          <li><a href="#">100</a></li>
          <li><a href="#">200</a></li>
        </ul>
      </div>
      </div>
    </div>
    <br>
     <div class="row">
      <div class="col-sm-6">
        <p>Check out</p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-6">
        <div class="dropdown">
      <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Min<span class="caret"></span></button>
        <ul class="dropdown-menu">
          <li><a href="#">100</a></li>
          <li><a href="#">200</a></li>
        </ul>
      </div>
      </div>
    </div>
    <br>
    <br>
    <div class="text-center">
      <button type="button" class="btn btn-info btn-md">Search</button>
    </div>
  </div>
</div>

app/views/bookings/_new.html.erb
<h1 class="text-center">Make a booking</h1>
<%= render 'form' %>

app/views/bookings/create.js.erb
$("#result_div").html( "<%= escape_javascript( render partial: 'new' ) %>");

app/views/bookings/index.js.erb
$("#result_div").html("<%= escape_javascript(render :partial => 'index')%>");

app/views/bookings/new.js.erb
$("#result_div").html("<%= escape_javascript( render :partial => 'new')%>");