config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  resources :customers
  resources :rooms do
      collection do
        get  :search
        post :new_search
        get  :show_search
        get  :search_by_room_type_id
      end

  end 
  resources :room_types
  resources :bookings
  resources :billings

  get 'welcome/index'

  # root 'welcome#index'
  root 'sessions#new'
  
  get 'login', to: 'sessions#new'
  
  delete 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
</head>
<body>

<nav class="navbar navbar-inverse bg-primary">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">   
        <% if !logged_in? %>
            <li><%= link_to "Log in", login_path %></li>
        <% else %> 
            <li><%= link_to "Rooms", rooms_path, remote: true, id:'list_rooms' %></li>
            <li><%= link_to "Room types", room_types_path, remote: true, id:'list_room_types' %></li>
            <li><%= link_to "Bookings", bookings_path, remote: true, id:'list_bookings'%></li>
            <li><%= link_to "Customers", customers_path, remote: true, id:'list_customers' %></li>
            <li><%= link_to "Staffs", customers_path, remote: true, id:'list_customers' %></li> 
            <% user = current_user %>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% end%>
      </ul>
    </div>
  </div>
</nav>
  
<div id="result_div" class="well">
 
  <% flash.each do |type, message|%>
      <%=message %>
  <% end%>

</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" id="modal-title-id"></h4>
      </div>
      <div class="modal-body" id="modal-body-id">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<footer class="container-fluid text-left navbar-fixed-bottom footer">
  <p>Footer Text</p>
</footer>
</body>
</html>