config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  resources :customers
  resources :rooms do
      collection do
        get  :search
        post :new_search
        get  :show_search
        get  :search_by_room_type_id
      end

  end 
  resources :room_types
  resources :bookings
  resources :billings

  get 'welcome/index'

  # root 'welcome#index'
  root 'sessions#new'
  
  get 'login', to: 'sessions#new'
  
  delete 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/room_types_controller.rb
class RoomTypesController < ApplicationController

	before_action :must_login

	def index

		@roomTypes = RoomType.all

		respond_to do |format|
			format.html
			format.js
		end
	end

	def new		
		@roomType = RoomType.new

		respond_to do |format|
			format.html
			format.js
		end
	end

	def create
		
		@roomType = RoomType.new( room_type_params )

		if @roomType.save
			self.index
		else
			respond_to do |format|
				format.html{ render partial: 'new' }
				format.js
			end	
		end
	end

	def edit

		@roomType = RoomType.find( params[:id] )

		respond_to do |format|
			format.html
			format.js
		end
	end

	def update

		@roomType = RoomType.find( params[:id])

		if @roomType.update( room_type_params )
			self.index
		else
			render 'edit'
		end
	end

	def show

		@roomType = RoomType.find( params[:id] )

		respond_to do |format|
			format.html
			format.js
		end
	end

	private 
		def room_type_params
			params.require(:room_type).permit(:name, :price, :number_of_beds, :ac, :description)
		end
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/views/room_types/_edit.html.erb
<h1>Editing room types</h1>
<%= render 'form' %>

app/views/room_types/_form.html.erb
<div class="well width60 center">
	<%= form_for @roomType, html:{:id => "create_room_type", :multipart => true, :remote => true } do |f| %>
		<% if @roomType.errors.any? %>
			<%= pluralize( @roomType.errors.count, "error" )%>
		<% end %>

		<ul>
			<% @roomType.errors.full_messages.each do |msg| %>
				<li><%=msg %></li>
			<% end %>
		</ul>

		<div class="container-fluid">
			<div class="form-group row">
				<div class="col-sm-4">	
					<%= f.label :name %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :name, :class => "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">	
					<%= f.label :price %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :price, :class => "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">	
					<%= f.label :number_of_beds %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :number_of_beds, :class => "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">	
					<%= f.label :ac %>
				</div>
				<div class="col-sm-8">
					<%= f.radio_button :ac, 'true'%> Yes <%= f.radio_button :ac, 'false'%> No
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<label for="description"><%= f.label :description %></label>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :description, :class => "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-6">
					<%= link_to 'Back', room_types_path , :class => "btn btn-danger left", :remote => true%>
				</div>
				<div class="col-sm-6">
					<%= f.submit :class => "btn btn-info right" %>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/room_types/_index.html.erb
<div class="row">
	<div class="col-sm-9">
		<div class="well">
			<div class="row">
				<div class="col-sm-9 bottom20"><h3>Listing room types</h3></div>
				<div class="col-sm-3">
				<%= link_to "Create room type", new_room_type_path, remote: true, id:'list_room_types', class:'btn btn-success btn-md float-right' %>
				</div>
			</div>
			<table class="table table-bordered">
				<tr>
					<th>Room type name</th>
					<th>Price</th>
					<th>Number of beds</th>
					<th>A/C</th>
					<th colspan="3" class="text-center">Action</th>
				</tr>
				 <% if @roomTypes.any? %>
					<% @roomTypes.each do |roomType| %>
						<tr>
							<td><%= roomType.name %></td>
							<td><%= roomType.price %></td>
							<td><%= roomType.number_of_beds %></td>
							<td><%= roomType.ac %></td>
							<td>
							<%= link_to 'Show', room_type_path( roomType ), :class => "glyphicon glyphicon-info-sign",
							:data => {:toggle => 'modal', :target => "#myModal"}, :remote => true %>
							</td>
							<td>
							<%= link_to 'Edit', edit_room_type_path( roomType ), :class => "glyphicon glyphicon-pencil", remote:true %>
							</td>	
							<td>
							<%= link_to 'Destroy', room_type_path( roomType ), :class => "glyphicon glyphicon-remove",method: :delete,
							data: { confirm: 'Are you sure?'}, remote:true %>
							</td>	
						</tr>
					<% end %>
				<%else %>
					<tr>
						<td colspan="7" class="text-center bg-info">
							<b>No record found</b>
						</td>
					</tr>
				<%end%>
			</table>
		</div>
	</div>

	<div class="col-sm-3 well">
		<h4>Search by</h4>
		<input class="form-control" id="myInput" type="text" placeholder="Room type name">
		<br>
		<div class="row">
			<div class="col-sm-6">
				<p>Price between</p>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-sm-6">
				<div class="dropdown">
		 	<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Min<span class="caret"></span></button>
			  <ul class="dropdown-menu">
			    <li><a href="#">100</a></li>
			    <li><a href="#">200</a></li>
			  </ul>
			</div>
			</div>
			<div class="col-sm-6">
				<div class="dropdown">
		 	<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Max<span class="caret"></span></button>
			  <ul class="dropdown-menu">
			    <li><a href="#">300</a></li>
			    <li><a href="#">400</a></li>
			  </ul>
			</div>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-sm-12">
				<div class="dropdown">
			 	<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Number of beds<span class="caret"></span></button>
				  <ul class="dropdown-menu">
				    <li><a href="#">1</a></li>
				    <li><a href="#">2</a></li>
				  </ul>
				</div>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-sm-12">
			 	<div class="dropdown">
				 	<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">A/C<span class="caret"></span></button>
					  <ul class="dropdown-menu">
					    <li><a href="#">Yes</a></li>
					    <li><a href="#">No</a></li>
					  </ul>
				</div>
			</div>
		</div> 
		<div class="text-center">
			<button type="button" class="btn btn-info btn-md">Search</button>
		</div>
	</div>
</div>

app/views/room_types/_new.html.erb
<h1 class="text-center">New room type</h1>
<%= render 'form' %>

app/views/room_types/_show.html.erb
<p>
	<strong>Name:</strong>
	<%= @roomType.name %>
</p>
<p>
	<strong>Cost:</strong>
	<%= @roomType.price %>
</p>

app/views/room_types/create.js.erb
$("#result_div").html("<%= escape_javascript(render partial: 'new')%>");

app/views/room_types/index.html.erb
<%= link_to 'View RoomTypes', controller: 'room_types'%>
<%= link_to 'Add room type', new_room_type_path %>

app/views/room_types/index.js.erb
$("#result_div").html("<%= escape_javascript(render :partial => 'index')%>");

app/views/room_types/new.html.erb
<h1>New Room type</h1>

<%= render "form" %>

app/views/room_types/new.js.erb
$("#result_div").html("<%= escape_javascript(render :partial => 'new')%>");

app/views/room_types/show.js.erb
$("#modal-body-id").html("<%= escape_javascript(render :partial => 'show')%>");
$("#modal-title-id").html("Room type details");

app/views/room_types/update.js.erb
$("#result_div").html("<%= escape_javascript(render :partial => 'index')%>");