config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  resources :customers
  resources :rooms do
      collection do
        get  :search
        post :new_search
        get  :show_search
        get  :search_by_room_type_id
      end

  end 
  resources :room_types
  resources :bookings
  resources :billings

  get 'welcome/index'

  # root 'welcome#index'
  root 'sessions#new'
  
  get 'login', to: 'sessions#new'
  
  delete 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room
  
  include Mongoid::Document
 
  field :room_number, type: String
  field :room_type_id, type: String
  field :availability, type: Boolean
  field :room_floor, type: Integer

  validates :room_number,  presence: true, uniqueness: true
  validates :room_type_id, :room_floor, presence: true
  validates :room_floor, numericality: { only_integer: true, allow_nil: false }

  belongs_to :room_type
  has_many   :bookings

 # has_many :customers, :through => :bookings
end

app/models/room_type.rb
class RoomType

  include Mongoid::Document

  field :name, type: String
  field :price, type: Float
  field :number_of_beds, type: Integer
  field :ac, type: Boolean
  field :description, type: String

  validates :name, presence: true, length: { in: 5..10}, uniqueness: true
  validates :price, presence: true, numericality: { allow_nil: false}
  validates :number_of_beds, presence: true, numericality:{ only_integer: true, allow_nil: false}
  validates :description, presence: true

  has_many :rooms, dependent: :destroy

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	
	before_action :must_login


	def index
		@rooms 		= Room.all
		@roomTypes 	= RoomType.all

		respond_to do |format|
			format.html
			format.js
		end
	end

	def show
		@room = Room.find(params[:id])

		respond_to do |format|
			format.html
			format.js
		end
	end

	def new
		@room = Room.new

		respond_to do |format|
			format.html
			format.js
		end
	end

	def edit
		@room = Room.find(params[:id])

		respond_to do |format|
			format.html
			format.js
		end
	end

	def create

		@room = Room.new( room_params )

		if @room.save
			self.index
		else
			# binding.pry
			respond_to do |format|
				format.html { render partial: 'new' }
				format.js
			end
		end

	end

	def update

		@room = Room.find( params[:id] )

		if @room.update( room_params )
			self.index
		else
			render 'edit'
		end

	end

	def destroy
		@room = Room.find(params[:id])
		@room.destroy

		self.index
	end

  	def search

    	@room_type_ids = params[:room_type_ids]
    	
    	@rooms = Room.where( :room_type_id =>{ "$in" => @room_type_ids } )

    	respond_to do |format|
    		format.html { render partial: 'search'  }
		end

  	end

  	def search_by_room_type_id

  		@room_type_id = params[:room_type_id]

  		@rooms = Room.where( :room_type_id => @room_type_id )

  		respond_to do |format|
  			format.html { render partial: 'search' }
		end

	end

	private 
		def room_params
			params.require(:room).permit( :room_number, :room_type_id, :availability, :room_floor )
		end
		
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_edit.html.erb
<h1 class="text-center">Editing room</h1>
<%= render 'form' %>

app/views/rooms/_form.html.erb
<div class="well width60 center">
	<%= form_for @room, :html =>{:id=>"create_room",:multipart => true,:remote=>true} do |f| %>
		<% if @room.errors.any? %>
			<div id="error_explanation" class="center">
				<h2>
				<%= pluralize(@room.errors.count, "error")%>prohibited this room from being saved:
				</h2>
				<ul>
					<% @room.errors.full_messages.each do |key, msg| %>
						<li><%=msg %> <%=key %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div class="container-fluid">
			<div class="form-group row">
				<div class="col-sm-4">
					<%= f.label :room_number %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :room_number, :class => "form-control" %>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-sm-4">
					<%= f.label :type %>
				</div>
				<div class="col-sm-8">
					<%= collection_select(:room, :room_type_id, RoomType.all, :id, :name) %>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-sm-4">
					<%= f.label :availability %>
				</div>
				<div class="col-sm-8">
	    			<%= f.radio_button :availability, 'true' %>Yes
	    			<%= f.radio_button :availability, 'false' %>No<br />
				</div>
			</div>

			<div class="form-group row">
				<div class="col-sm-4">
					<%= f.label :room_floor %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :room_floor, :class => "form-control" %>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-sm-6">
					<%= link_to 'Back', rooms_path , :class => "btn btn-danger left", remote: true %>
				</div>
				<div class="col-sm-6">
				</div>
				<div class="col-sm-6">
					<%= f.submit :class => "btn btn-info right", :id => "create_room" %>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/rooms/_index.html.erb
<div class="row">
	<div class="col-sm-9">
		<div class="well">
			<div class="row">
				<div class="col-sm-10 bottom20"><h3>Listing rooms</h3></div>
				
				<% if @roomTypes.any? %>
					<div class="col-sm-2">
						<%= link_to "Create room", new_room_path, remote: true, id:'list_rooms', 
				class:'btn btn-success btn-md float-right' %>
					</div>
				<% else%>
					<div class="alert alert-warning col-sm-6">
						<strong>Warning!</strong> Add at least one room type to create room.
					</div>
				<% end %>

			</div>
			<table class="table table-bordered">
				<tr>
					<th>Room number</th>
					<th>Type</th>
					<th>Availability</th>
					<th>Floor</th>
					<th colspan="3" class="text-center">Action</th>
				</tr>
				<% if @rooms.any? %>
					<% @rooms.each do |room| %>
						<tr>
							<td><%= room.room_number %></td>
							<% roomType = @roomTypes.find( room.room_type_id ) %></td>
							<td><%= roomType.name %></td>
							<td><%= room.availability %></td>
							<td><%= room.room_floor%></td>
							<td>
							<%= link_to 'Show', room_path( room ), :class => "glyphicon glyphicon-info-sign",
							:data => {:toggle => 'modal', :target => "#myModal"}, :remote => true %>
							</td>
							<td>
							<%= link_to 'Edit', edit_room_path( room ), :class => "glyphicon glyphicon-pencil", remote:true %>
							</td>	
							<td>
							<%= link_to 'Destroy', room_path( room ), :class => "glyphicon glyphicon-remove",method: :delete,
							data: { confirm: 'Are you sure?'}, remote:true %>
							</td>	
						</tr>
					<% end %>
				<% else %>
					<tr>
						<td colspan="7" class="text-center bg-info">
							<b>No record found</b>
						</td>
					</tr>
				<% end%>
			</table>
		</div>
	</div>

	<div class="col-sm-3 well">
		<h4>Search by</h4>
		<input class="form-control" id="myInput" type="text" placeholder="Room number">
		<br>
		<div class="row">
			<div class="col-sm-6">
				<p>Room type</p>
				<div class="checkbox">
					<label><input type="checkbox" value="">Option 1</label>
				</div>
				<div class="checkbox">
					<label><input type="checkbox" value="">Option 2</label>
				</div>
				<div class="checkbox">
					<label><input type="checkbox" value="">Option 3</label>
				</div> 
			</div>
			<div class="col-sm-6">
				<p>Floor</p>
				<div class="checkbox">
					<label><input type="checkbox" value="">Option 1</label>
				</div>
				<div class="checkbox">
					<label><input type="checkbox" value="">Option 2</label>
				</div>
				<div class="checkbox">
					<label><input type="checkbox" value="">Option 3</label>
				</div>		
			</div>
		</div>
		<br>
	 	<div class="dropdown">
		 	<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Availability<span class="caret"></span></button>
			  <ul class="dropdown-menu">
			    <li><a href="#">Yes</a></li>
			    <li><a href="#">No</a></li>
			  </ul>
		</div>
		<br>
		<div class="text-center">
			<button type="button" class="btn btn-info btn-md">Search</button>
		</div>
	</div>
</div>
<script type="text/javascript">
	
	
$(document).on('ready page:change', function() {
  $('input[type="checkbox"].toggle').bootstrapToggle(); 
  // assumes the checkboxes have the class "toggle"
});
</script>

app/views/rooms/_new.html.erb
<h1 class="text-center">Create a new room</h1>
<%= render 'form' %>

app/views/rooms/_search.html.erb
<% @rooms.each do |room| %>
	 <input type="checkbox" name="booking[room_ids][]" value="<%=room.id %>" class="chk_room">
	 <label for="<%=room.room_number %>"><%=room.room_number %></label>
<% end%>

app/views/rooms/_show.html.erb
<p>
	<strong>Name:</strong>
	<%= @room.room_number %>
</p>
<p>
	<strong>Cost:</strong>
	<%= @room.room_floor %>
</p>

app/views/rooms/create.js.erb
$("#result_div").html("<%= escape_javascript(render partial: 'new')%>");

app/views/rooms/destroy.js.erb
$("#result_div").html("<%= escape_javascript(render :partial => 'index')%>");

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/new.html.erb
<h1 class="text-center">New room</h1>
<button type="button" class="close" data-dismiss="modal">Close</button>
<%= render 'form' %>

app/views/rooms/search.js.erb
$("#display_rooms").html("<%= escape_javascript( render :partial => 'search') %>");

app/views/rooms/show.html.erb
<p>
	<strong>Name:</strong>
	<%= @room.name %>
</p>
<p>
	<strong>Cost:</strong>
	<%= @room.price %>
</p>

app/views/rooms/show.js.erb
$("#modal-body-id").html("<%= escape_javascript(render :partial => 'show')%>");
$("#modal-title-id").html("Room detail")

app/views/rooms/update.js.erb
$("#result_div").html("<%= escape_javascript(render :partial => 'index')%>");